# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i-nb49FP9Z58_H1Cy7Ch0lhYg-d5IVep
"""

import pickle

f=open('drive/My Drive/Colab Notebooks/data/neo4j/component_mapping.pickle','rb') # modify path to your file 
bb=pickle.load(f)

import csv

source=open('drive/My Drive/Colab Notebooks/data/neo4j/US.txt','r')
csvFile=open('drive/My Drive/Colab Notebooks/data/neo4j/result.csv','w',newline='')
writer = csv.writer(csvFile)

source.seek(0)

i = 0
title = ['productId','userId']
writer.writerow(title)

line = source.readline()
while line: 
    i += 1
    productId = line.replace('\n','')
    movieSet = bb.get(productId) # find parent productId
    if movieSet is None:
      print("can't find " + line) # continue to next [productId, userId]
      line = source.readline()
      line = source.readline()
      continue
    movieSet = (list)(movieSet) 
    line = source.readline()        
    userId = line.replace('\n','')
    line = source.readline()
    row = [movieSet[0], userId] # insert parent productId into row
    if(i % 500 == 0):
      print("i:" + str(i) + " content: "+ str(row)) # print per 500 loop
    writer.writerow(row)

source.close()
csvFile.close()
f.close()